name: Train Goldfish YOLO (PR)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ultralytics
        run: |
          python -m pip install --upgrade pip
          pip install ultralytics==8.2.103

      - name: Train (CPU)
        run: |
          yolo detect train data=demo_goldfish_dataset/data.yaml model=yolov8n.pt epochs=30 imgsz=640 batch=16 device=cpu
          mkdir -p weights
          cp runs/detect/*/weights/best.pt weights/goldfish_best.pt

      - name: Create PR with weights
        uses: peter-evans/create-pull-request@v6
        with:
          branch: weights/update
          commit-message: "Add/update goldfish weights"
          title: "Add/update goldfish weights"
          body: "Automated training run"
          add-paths: |
            weights/goldfish_best.pt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: goldfish_best.pt
          path: weights/goldfish_best.pt
